name: Build PDF + Deploy Docs

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
  schedule:
    - cron: '0 4 * * *'  # Nightly at 4:00 UTC

jobs:
  pdfhtml:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[sphinx,pdfhtml]
      - name: Install Playwright CLI
        run: npm install -g playwright
      - name: Install Playwright browser deps
        run: playwright install --with-deps chromium
      - name: Build PDF (HTML via Playwright)
        run: jb build docs --builder pdfhtml -n -W --keep-going
      - uses: actions/upload-artifact@v4
        with:
          name: PDF_HTML
          path: docs/_build/pdf/book.pdf

  pdflatex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[sphinx,pdflatex]
      - name: Install LaTeX dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y     \
            texlive-latex-recommended \
            texlive-latex-extra       \
            texlive-fonts-extra       \
            fonts-freefont-otf        \
            texlive-xetex             \
            latexmk                   \
            xindy                     \
            imagemagick
      - name: Build PDF (LaTeX)
        run: jb build docs --builder pdflatex -n -W --keep-going
      - uses: actions/upload-artifact@v4
        with:
          name: PDF_LATEX
          path: docs/_build/latex/book.pdf

  zip_all:
    runs-on: ubuntu-latest
    needs: [pdfhtml, pdflatex]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Zip PDFs
        run: |
          mkdir -p combined
          cp PDF_HTML/book.pdf combined/book_html.pdf || true
          cp PDF_LATEX/book.pdf combined/book_latex.pdf || true
          zip -r docs_output.zip combined
      - uses: actions/upload-artifact@v4
        with:
          name: ALL_PDFS
          path: docs_output.zip

  deploy-html:
    runs-on: ubuntu-latest
    needs: [pdfhtml]  # Only needs HTML builder
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .[sphinx]
      - name: Build HTML docs
        run: jb build docs --builder html -n -W --keep-going
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html